# Generated by Django 5.2.13 on 2026-05-01 16:51

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_type', models.CharField(choices=[('FREE', 'Grátis'), ('PRO', 'PRO')], default='FREE', max_length=10, verbose_name='plano')),
                ('status', models.CharField(choices=[('ACTIVE', 'Ativa'), ('TRIALING', 'Em período de teste'), ('PAST_DUE', 'Pagamento atrasado'), ('CANCELED', 'Cancelada')], default='ACTIVE', max_length=12, verbose_name='status')),
                ('gateway_subscription_id', models.CharField(blank=True, default='', max_length=120, verbose_name='ID externo no gateway')),
                ('current_period_end', models.DateTimeField(blank=True, null=True, verbose_name='renovação em')),
                ('cancel_at_period_end', models.BooleanField(default=False, verbose_name='cancelar ao final do período')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='subscription', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'assinatura',
                'verbose_name_plural': 'assinaturas',
            },
        ),
    ]
