# Generated by Django 5.2.13 on 2026-05-01 17:11

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('billing', '0002_coupon'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='coupon',
            name='max_per_user',
            field=models.PositiveIntegerField(default=1, help_text='Cada usuário pode usar este cupom no máximo X vezes.', verbose_name='usos máximos por usuário'),
        ),
        migrations.AlterField(
            model_name='coupon',
            name='max_uses',
            field=models.PositiveIntegerField(default=1, help_text='Quantidade total de usos do cupom (todos os usuários somados).', verbose_name='usos totais máximos'),
        ),
        migrations.CreateModel(
            name='CouponRedemption',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('user_name_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('user_email_snapshot', models.CharField(blank=True, default='', max_length=255)),
                ('discount_percent', models.PositiveSmallIntegerField()),
                ('final_price_brl', models.DecimalField(decimal_places=2, max_digits=10)),
                ('redeemed_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('coupon', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='redemptions', to='billing.coupon')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='coupon_redemptions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'uso de cupom',
                'verbose_name_plural': 'usos de cupons',
                'ordering': ['-redeemed_at'],
                'indexes': [models.Index(fields=['coupon', '-redeemed_at'], name='billing_cou_coupon__e833bd_idx'), models.Index(fields=['user', '-redeemed_at'], name='billing_cou_user_id_da3a71_idx')],
            },
        ),
    ]
