# Generated by Django 5.2.13 on 2026-05-01 16:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0003_seed_pet_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='AuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('actor_name_snapshot', models.CharField(help_text='Preservado mesmo se a conta for excluída.', max_length=255, verbose_name='nome do ator (snapshot)')),
                ('actor_role_snapshot', models.CharField(blank=True, default='', max_length=20, verbose_name='papel do ator')),
                ('action', models.CharField(choices=[('CREATE', 'Criou'), ('UPDATE', 'Atualizou'), ('DELETE', 'Excluiu'), ('REVOKE', 'Revogou'), ('CLAIM', 'Acessou via PIN')], max_length=20, verbose_name='ação')),
                ('entity_type', models.CharField(max_length=50, verbose_name='tipo de entidade')),
                ('entity_id', models.UUIDField(blank=True, null=True, verbose_name='id da entidade')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='descrição')),
                ('changes', models.JSONField(blank=True, default=dict, verbose_name='alterações')),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.CharField(blank=True, default='', max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='data/hora')),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_actions', to=settings.AUTH_USER_MODEL, verbose_name='ator')),
                ('pet', models.ForeignKey(blank=True, help_text='Pet relacionado (facilita filtros por prontuário).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_logs', to='pets.pet')),
            ],
            options={
                'verbose_name': 'registro de auditoria',
                'verbose_name_plural': 'registros de auditoria',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['pet', '-created_at'], name='audit_audit_pet_id_2c6193_idx'), models.Index(fields=['actor', '-created_at'], name='audit_audit_actor_i_1175ab_idx'), models.Index(fields=['entity_type', 'entity_id'], name='audit_audit_entity__9535bf_idx')],
            },
        ),
    ]
