# Generated by Django 5.2.12 on 2026-04-06 16:42

import access.models
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='VetAccessToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('access_code', models.CharField(default=access.models.generate_access_code, max_length=6, verbose_name='código de acesso')),
                ('expires_at', models.DateTimeField(verbose_name='expira em')),
                ('is_active', models.BooleanField(default=True, verbose_name='ativo')),
                ('is_used', models.BooleanField(default=False, verbose_name='utilizado')),
                ('deleted_at', models.DateTimeField(blank=True, null=True, verbose_name='excluído em')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'token de acesso veterinário',
                'verbose_name_plural': 'tokens de acesso veterinário',
            },
        ),
    ]
