# Generated by Django 5.2.12 on 2026-04-06 16:42

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('access', '0001_initial'),
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='vetaccesstoken',
            name='pet',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='access_tokens', to='pets.pet', verbose_name='pet'),
        ),
        migrations.AddField(
            model_name='vetaccesstoken',
            name='vet',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vet_access_tokens', to=settings.AUTH_USER_MODEL, verbose_name='veterinário'),
        ),
    ]
