# Generated by Django 5.2.13 on 2026-05-01 14:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='vetaccesstoken',
            name='claimed_at',
            field=models.DateTimeField(blank=True, help_text='Quando o veterinário fez o claim do PIN.', null=True, verbose_name='usado em'),
        ),
    ]
