# Generated by Django 5.2.13 on 2026-05-01 18:15

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0003_vetaccesstoken_claimed_at'),
        ('pets', '0003_seed_pet_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='vetaccesstoken',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True), ('is_active', True), ('is_used', False)), fields=('access_code',), name='uniq_active_access_code'),
        ),
    ]
