# Generated by Django 5.2.13 on 2026-05-01 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('access', '0004_vetaccesstoken_uniq_active_access_code'),
        ('pets', '0004_pet_pets_pet_tutor_i_98f4e3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='vetaccesstoken',
            index=models.Index(fields=['access_code'], name='access_veta_access__e8e985_idx'),
        ),
        migrations.AddIndex(
            model_name='vetaccesstoken',
            index=models.Index(fields=['pet', 'vet', 'is_active'], name='access_veta_pet_id_0c3432_idx'),
        ),
    ]
