# Generated by Django 5.2.13 on 2026-05-01 22:04

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0005_passwordresettoken'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='NotificationPreference',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='notif_prefs', serialize=False, to=settings.AUTH_USER_MODEL)),
                ('push_vaccine', models.BooleanField(default=True)),
                ('push_vet_return', models.BooleanField(default=True)),
                ('push_payment_due', models.BooleanField(default=True)),
                ('push_payment_ok', models.BooleanField(default=True)),
                ('push_pin_generated', models.BooleanField(default=True)),
                ('push_vet_access_claimed', models.BooleanField(default=True)),
                ('push_system', models.BooleanField(default=True)),
                ('email_enabled', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='DevicePushToken',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('platform', models.CharField(choices=[('ios', 'iOS'), ('android', 'Android'), ('web', 'Web')], max_length=10)),
                ('expo_push_token', models.CharField(blank=True, default='', max_length=255)),
                ('web_push_endpoint', models.URLField(blank=True, default='', max_length=500)),
                ('web_push_p256dh', models.CharField(blank=True, default='', max_length=255)),
                ('web_push_auth', models.CharField(blank=True, default='', max_length=255)),
                ('last_seen', models.DateTimeField(auto_now=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='push_tokens', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'constraints': [models.UniqueConstraint(condition=models.Q(('expo_push_token', ''), _negated=True), fields=('expo_push_token',), name='uniq_expo_push_token'), models.UniqueConstraint(condition=models.Q(('web_push_endpoint', ''), _negated=True), fields=('web_push_endpoint',), name='uniq_web_push_endpoint')],
            },
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VACCINE', 'Vacina'), ('VET_RETURN', 'Retorno ao vet'), ('PAYMENT_DUE', 'Vencimento de pagamento'), ('PAYMENT_OK', 'Pagamento confirmado'), ('PIN_GENERATED', 'PIN criado'), ('VET_ACCESS_CLAIMED', 'Vet acessou prontuário'), ('SYSTEM', 'Sistema')], max_length=32)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('data', models.JSONField(blank=True, default=dict)),
                ('read_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['user', '-created_at'], name='notificatio_user_id_05b4bc_idx'), models.Index(fields=['user', 'read_at'], name='notificatio_user_id_47e85c_idx')],
            },
        ),
    ]
