# Generated by Django 5.2.13 on 2026-05-01 13:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='address_city',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='cidade'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_complement',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='complemento'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_district',
            field=models.CharField(blank=True, default='', max_length=120, verbose_name='bairro'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_number',
            field=models.CharField(blank=True, default='', max_length=20, verbose_name='número'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_state',
            field=models.CharField(blank=True, default='', max_length=2, verbose_name='estado/UF'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_street',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='rua/logradouro'),
        ),
        migrations.AddField(
            model_name='user',
            name='address_zip',
            field=models.CharField(blank=True, default='', max_length=10, verbose_name='CEP'),
        ),
        migrations.AddField(
            model_name='user',
            name='clinic_name',
            field=models.CharField(blank=True, default='', help_text='Apenas para veterinários.', max_length=255, verbose_name='nome da clínica/consultório'),
        ),
        migrations.AddField(
            model_name='user',
            name='document',
            field=models.CharField(blank=True, default='', help_text='CPF do tutor (opcional). Pode estar mascarado.', max_length=14, verbose_name='CPF'),
        ),
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(blank=True, default='', help_text='Número com DDD. Ex.: (11) 99999-9999', max_length=20, verbose_name='telefone/celular'),
        ),
        migrations.AddField(
            model_name='user',
            name='whatsapp',
            field=models.BooleanField(default=False, help_text='Este número pode receber mensagens via WhatsApp.', verbose_name='aceita WhatsApp'),
        ),
    ]
