# Generated by Django 5.2.13 on 2026-05-01 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_address_city_user_address_complement_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='must_change_password',
            field=models.BooleanField(default=False, help_text='Marcado quando o usuário foi criado por outra pessoa (ex.: tutor convidando familiar) com senha temporária. Frontend força tela de troca antes de liberar o app.', verbose_name='deve trocar a senha no próximo login'),
        ),
    ]
