# Generated by Django 5.2.13 on 2026-05-01 17:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_user_must_change_password'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('TUTOR', 'Tutor'), ('VET', 'Veterinário'), ('ADMIN', 'Administrador')], default='TUTOR', max_length=10, verbose_name='papel'),
        ),
    ]
