# Generated by Django 5.2.12 on 2026-04-06 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=120, verbose_name='nome')),
                ('species', models.CharField(choices=[('DOG', 'Cachorro'), ('CAT', 'Gato'), ('BIRD', 'Pássaro'), ('OTHER', 'Outro')], default='DOG', max_length=10, verbose_name='espécie')),
                ('breed', models.CharField(blank=True, default='', max_length=120, verbose_name='raça')),
                ('weight_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, verbose_name='peso (kg)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tutor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='tutor')),
            ],
            options={
                'verbose_name': 'pet',
                'verbose_name_plural': 'pets',
                'ordering': ['name'],
            },
        ),
    ]
