# Generated by Django 5.2.13 on 2026-05-01 15:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='tutor',
            field=models.ForeignKey(help_text='Tutor proprietário (OWNER). Mantido para compatibilidade. A relação canônica de membros está em PetMember.', on_delete=django.db.models.deletion.CASCADE, related_name='pets', to=settings.AUTH_USER_MODEL, verbose_name='tutor'),
        ),
        migrations.CreateModel(
            name='PetMember',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('OWNER', 'Tutor principal'), ('CARETAKER', 'Familiar / cuidador')], default='CARETAKER', max_length=12, verbose_name='papel')),
                ('added_at', models.DateTimeField(auto_now_add=True, verbose_name='adicionado em')),
                ('added_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='invited_pet_memberships', to=settings.AUTH_USER_MODEL, verbose_name='convidado por')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='members', to='pets.pet', verbose_name='pet')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pet_memberships', to=settings.AUTH_USER_MODEL, verbose_name='usuário')),
            ],
            options={
                'verbose_name': 'membro do pet',
                'verbose_name_plural': 'membros do pet',
                'ordering': ['pet', '-added_at'],
                'unique_together': {('pet', 'user')},
            },
        ),
    ]
