# Generated by Django 5.2.13 on 2026-05-01 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pets', '0003_seed_pet_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='pet',
            index=models.Index(fields=['tutor'], name='pets_pet_tutor_i_98f4e3_idx'),
        ),
        migrations.AddIndex(
            model_name='petmember',
            index=models.Index(fields=['pet', 'role'], name='pets_petmem_pet_id_f31e16_idx'),
        ),
        migrations.AddIndex(
            model_name='petmember',
            index=models.Index(fields=['user'], name='pets_petmem_user_id_f5aa0e_idx'),
        ),
    ]
