# Generated by Django 5.2.12 on 2026-04-06 16:42

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pets', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('record_type', models.CharField(choices=[('VACCINE', 'Vacina'), ('EXAM', 'Exame'), ('PRESCRIPTION', 'Receita'), ('SURGERY', 'Cirurgia'), ('NOTE', 'Anotação')], max_length=20, verbose_name='tipo de registro')),
                ('title', models.CharField(max_length=255, verbose_name='título')),
                ('description', models.TextField(blank=True, default='', verbose_name='descrição')),
                ('date_occurred', models.DateField(verbose_name='data de ocorrência')),
                ('raw_extracted_text', models.TextField(blank=True, default='', help_text='Texto bruto extraído de documentos enviados.', verbose_name='texto extraído (OCR)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='authored_records', to=settings.AUTH_USER_MODEL, verbose_name='autor')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='health_records', to='pets.pet', verbose_name='pet')),
            ],
            options={
                'verbose_name': 'registro de saúde',
                'verbose_name_plural': 'registros de saúde',
                'ordering': ['-date_occurred'],
            },
        ),
    ]
