# Generated by Django 5.2.13 on 2026-05-01 16:18

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HealthRecordAttachment',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('storage_key', models.CharField(help_text='Caminho/ID do arquivo no backend de storage.', max_length=512, verbose_name='chave do storage')),
                ('file_name', models.CharField(max_length=255, verbose_name='nome do arquivo')),
                ('description', models.CharField(blank=True, default='', max_length=500, verbose_name='descrição')),
                ('mime_type', models.CharField(blank=True, default='', max_length=120, verbose_name='tipo MIME')),
                ('file_size', models.PositiveIntegerField(default=0, verbose_name='tamanho (bytes)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('record', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='health.healthrecord', verbose_name='registro de saúde')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='uploaded_attachments', to=settings.AUTH_USER_MODEL, verbose_name='enviado por')),
            ],
            options={
                'verbose_name': 'anexo',
                'verbose_name_plural': 'anexos',
                'ordering': ['-created_at'],
            },
        ),
    ]
