# Generated by Django 5.2.13 on 2026-05-01 22:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0002_healthrecordattachment'),
        ('pets', '0003_seed_pet_owners'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reminder',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('type', models.CharField(choices=[('VACCINE', 'Vacina'), ('VET_RETURN', 'Retorno ao vet'), ('CUSTOM', 'Personalizado')], max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('description', models.TextField(blank=True, default='')),
                ('date_due', models.DateField()),
                ('notified_at', models.DateTimeField(blank=True, null=True)),
                ('dismissed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_reminders', to=settings.AUTH_USER_MODEL)),
                ('health_record', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reminders', to='health.healthrecord')),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reminders', to='pets.pet')),
            ],
            options={
                'ordering': ['date_due', '-created_at'],
                'indexes': [models.Index(fields=['pet', 'date_due'], name='health_remi_pet_id_0f9200_idx'), models.Index(fields=['date_due', 'notified_at', 'dismissed_at'], name='health_remi_date_du_eff345_idx')],
            },
        ),
    ]
