# Generated by Django 5.2.13 on 2026-05-01 23:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('health', '0003_reminder'),
        ('pets', '0004_pet_pets_pet_tutor_i_98f4e3_idx_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['pet', '-date_occurred'], name='health_heal_pet_id_47a10d_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecord',
            index=models.Index(fields=['record_type'], name='health_heal_record__44a9cb_idx'),
        ),
        migrations.AddIndex(
            model_name='healthrecordattachment',
            index=models.Index(fields=['record'], name='health_heal_record__df86ef_idx'),
        ),
    ]
